site_name: Programmation 1 - Automne 2022
theme:
    name: material
nav:
    - Accueil: index.md
    - Notes de cours :
        - Semaine 1 - Introduction à la programmation : introduction-programmation.md
        - Semaine 2 - ... : enconstruction.md
        - Semaine 3 - ... : enconstruction.md
        - Semaine 4 - ... : enconstruction.md
        - Semaine 5 - ... : enconstruction.md
        - Semaine 6 - ... : enconstruction.md
        - Semaine 7 - ... : enconstruction.md
        - Semaine 8 - ... : inenconstructiondex.md
        - Semaine 9 - ... : enconstruction.md
        - Semaine 10 - ... : enconstruction.md
        - Semaine 11 - ... : enconstruction.md
        - Semaine 12 - ... : enconstruction.md
        - Semaine 13 - ... : enconstruction.md
        - Semaine 14 - ... : enconstruction.md
        - Semaine 15 - ... : enconstruction.md
    - Exercices :
        - Semaine 1 - Exercice 1 : 'exercices/introduction-programmation.md'
        - Semaine 2 - Exercice 2 : enconstruction
    - À propos: 
        - À propos : apropos.md
        - Procédure : procedure.md