site_name: Programmation 1 - Automne 2022
theme:
    name: material
nav:
    - Accueil: index.md
    - Notes de cours :
        - Semaine 1 :
            - Introduction à la programmation : introduction-programmation.md
            - Débogage : enconstruction.md
            - Concepts fondamentaux : concepts-fondamentaux.md
        - Semaine 2 - ... : enconstruction.md
        - ... : enconstruction.md
    - Exercices :
        - Semaine 1 - Introduction à la programmation : 'exercices/introduction-programmation.md'
        - Semaine 2 - ... : enconstruction.md
        - ... :  enconstruction.md
    - À propos: 
        - Origine du projet : PRF610.md
        - Procédure : procedure.md