site_name: Programmation 1 - Automne 2022
nav:
    - Accueil: index.md
    - À propos: 
        - À propos : apropos.md
        - Procédure : procedure.md
    - Notes de cours :
        - Semaine 1 - Introduction à la programmation : introduction-programmation.md
        - Semaine 2 - Instruction d'entrées et sorties : instructions-entrees-sorties.md
    - Exercices :
        - Semaine 1 - Exercice 1 : 'exercices/introduction-programmation.md'
        - Semaine 2 - Exercice 2 : 'exercices/instructions-entrees-sorties.md'